version: "3.7"
services:
  server:
    image: labstore-tomcat:0.1
    build:
      context: ./server
    env_file:
      - .env
    ports:
      - "${WEB_PORT}:8080"
    restart: always
    depends_on:
      - db
    volumes:
      - ${DATA_PATH_HOST}/server/temp:/usr/local/tomcat/temp
      - ${DATA_PATH_HOST}/server/logs:/usr/local/tomcat/logs
      - ${DATA_PATH_HOST}/server/images:/usr/local/tomcat/images
  db:
    image: labstore-mysql:0.1
    build:
      context: ./mysql
    ports:
      - "${DB_PORT}:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      # MYSQL_USER: ${DB_USER}
      # MYSQL_PASSWORD: ${DB_PASSWORD}
      # MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql